feat: skip installation of attic when installed
ryanccn/attic-action pull request #21
Opened 2024-05-17 15:07 UTC by pfzetto

As proposed in #20 this PR adds a check to skip the installation of `attic` when `attic -V` returns with exit code 0.

2024-05-17 15:11 UTC, ryanccn requested changes
Please use the designated formatter (Prettier)! `pnpm run format` should do the trick.

2024-05-17 15:11 UTC, ryanccn commented on src/stages/install.ts
> +export const is_installed = async () => {
```suggestion
export const isInstalled = async () => {
```

2024-05-17 15:11 UTC, ryanccn commented on src/stages/install.ts
> +    return return_code==0;
```suggestion
    return return_code === 0;
```

2024-05-17 15:52 UTC, pfzetto commented
Sorry, I implemented the suggested changes and ran the formatter.

2024-05-25 07:32 UTC, getchoo approved these changes
lgtm

2024-05-25 08:29 UTC, ryanccn approved these changes

2024-05-25 08:29 UTC, merged